type User {
  id: ID!
  username: String!
  pets: [Pet]!
}

interface Animal {
  legs: Int!
  age: Int!
}

type Dog implements Animal {
  legs: Int!
  age: Int!
  bhow: Boolean!
}

type Cat implements Animal {
  legs: Int!
  age: Int!
  meow: Boolean!
}

enum PetTypes {
  DOG
  CAT
}

type Pet {
  id: String!
  createdAt: String!
  name(up: Boolean): String!
  type: PetTypes!
  img: String!
  user: User!
}
